all:
  vars:
    initial_user: root
    deployment_user: deployment
    user_password: "" # Add user password as vault variable
    ssh_users: "{{ deployment_user }}"
    user_authorized_keys: [] # Add list of SSH public keys
    docker__version: "27.1.1"
    docker_data_root: /srv/docker
    certbot_config_dir: /srv/config/certbot
    gateway_config_dir: /srv/config/gateway
    mc_config_dir: /srv/config/mc
    mc_container_image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    locations_conf: config/nginx/locations.conf.j2
    root_app: frontend
    nginx_conf: config/nginx/nginx.conf
    server_conf: config/nginx/server.conf.j2
    create_dhparam: false
    set_uid_and_gid_script: config/nginx/00-set-uid-and-gid.sh.j2
    compose_file: config/compose/docker-compose.yml.j2
    download_dir: "/home/{{ deployment_user }}/downloads"
    compose_dir: "/home/{{ deployment_user }}/compose"
    certbot_email: stefan.dieterle@artcom.de
    webserver_uid: 10001
    webserver_gid: 10001
    static_volume: static
    static_directory: "{{ docker_data_root }}/volumes/{{ compose_project_name }}_{{ static_volume }}/_data"
    cms_database_volume: cms-db
    cms_static_volume: cms-static
    cms_media_volume: cms-media
    database_user: cheminova
    database_password: "" # Add database password as vault variable
    database_name: cheminova
    cms_secret_key: "" # Add Django secret key as vault variable
    buckets:
      cheminova:
        name: cheminova # S3 bucket name
        endpoint: "" # s3 endpoint url
        access_key: "" # Add access key as vault variable
        secret_key: "" # Add secret key as vault variable
    media_backup_path: media # relative path inside the bucket
    db_dump_path: db-dump # relative path inside the bucket

  hosts:
    cheminova.example.com: # Replace with your domain
      local_hostname: cheminova
      compose_project_name: cheminova
      backend_version: v2.8.4
      mc_alias: cheminova
      bucket_name: "{{ buckets[mc_alias].name }}"
      bucket_database_backup: "{{ bucket_name }}/db-dump"
      bucket_media_backup: "{{ bucket_name }}/media"
      certbot_compose_project_name: "{{ compose_project_name }}"
      certbot_challenge: http
      wagtailadmin_base_url: "https://{{ inventory_hostname }}/cms/"
      api_base_url: "https://{{ inventory_hostname }}/cms/api/"
